import type { Metadata } from 'next';
import { SectionIntro } from '@/components/SiteShell';
export const metadata: Metadata = { title: 'Wie wir arbeiten', description: 'Wie Konomic Erstkontakt, frühe Prüfung, Unterlagen, mehrsprachige Kommunikation und Remote-Start für internationale Mandanten auf Teneriffa handhabt.', alternates: { canonical: '/de/how-we-work' } };
const firstContact=['Für die meisten neuen Anliegen sollte die erste Nachricht per WhatsApp beginnen.','Wenn der Fall noch in einem frühen Stadium ist, reicht meist eine kurze Zusammenfassung.','Wenn Unterlagen bereits vorliegen, können sie in der Regel nach dem Erstkontakt geteilt werden.'];
const reviewLogic=['Der Sachverhalt wird früh geprüft, um den richtigen nächsten Schritt zu erkennen.','Ziel ist Klarheit, bevor das Problem teurer oder komplizierter wird.','Das erste nützliche Ergebnis ist meist nicht „alles ist gelöst“, sondern ein klarerer rechtlicher Weg.'];
const documents=['Vertragsentwürfe oder bereits unterschriebene Dokumente','Immobilienunterlagen oder Objektreferenzen','Unterlagen zu Aufenthalt oder lokalen Registrierungen','Unternehmensentwürfe, Vereinbarungen oder Handelsdokumente'];
const remotePoints=['Viele internationale Mandanten beginnen vor der Anreise nach Teneriffa.','Dokumentenprüfung kann oft remote beginnen, wenn es sinnvoll ist.','WhatsApp, Telegram und E-Mail ermöglichen einen praktischen ersten Schritt.'];
const processSteps=['Der Mandant sendet die erste Nachricht, meist per WhatsApp.','Der Sachverhalt wird geprüft und dem passenden Beratungs- oder Prüfungsformat zugeordnet.','Falls nötig, werden Unterlagen vorab geteilt.','Danach wird klar, was jetzt wichtig ist und was warten kann.'];
export default function Page(){return <main className="ui-section ui-section-cool"><SectionIntro eyebrow="Wie wir arbeiten" title="Ein klarerer Prozess für internationale Mandanten mit juristischen Fragen auf Teneriffa" text="Diese Seite erklärt, wie Konomic Erstkontakt, frühe Prüfung, Unterlagen, Beratungsablauf und mehrsprachige Kommunikation für Mandanten handhabt, die vor Unterschrift, Umzug, Investition oder Strukturierung rechtliche Klarheit brauchen." /><div className="mt-8 ui-rule" /><div className="mt-12 grid gap-6 lg:grid-cols-2"><div className="ui-card p-8 md:p-10"><div className="text-xs uppercase tracking-[0.28em] text-[#9a6200]">Erstkontakt</div><h2 className="mt-3 text-2xl font-semibold tracking-tight">Mit einer kurzen Nachricht beginnen, nicht mit einem langen Formular</h2><ul className="mt-6 space-y-4 text-sm leading-7 text-[#56616b] md:text-base">{firstContact.map((item)=><li key={item}>• {item}</li>)}</ul></div><div className="ui-card-dark p-8 text-white md:p-10"><div className="relative z-10"><div className="text-xs uppercase tracking-[0.28em] text-[#fca311]">Frühe Prüfung</div><h2 className="mt-3 text-2xl font-semibold tracking-tight">Das erste Ziel ist Klarheit, nicht Komplexität</h2><ul className="mt-6 space-y-4 text-sm leading-7 text-white/82 md:text-base">{reviewLogic.map((item)=><li key={item}>• {item}</li>)}</ul></div></div></div><div className="mt-12 grid gap-6 lg:grid-cols-[1.05fr_0.95fr]"><div className="ui-card p-8 md:p-10"><div className="text-xs uppercase tracking-[0.28em] text-[#9a6200]">Unterlagen</div><h2 className="mt-3 text-2xl font-semibold tracking-tight">Was Mandanten häufig vor dem nächsten Schritt senden</h2><div className="mt-6 grid gap-3">{documents.map((item)=><div key={item} className="ui-card-soft px-4 py-4 text-sm text-[#33404a]">{item}</div>)}</div></div><div className="ui-card p-8 md:p-10"><div className="text-xs uppercase tracking-[0.28em] text-[#9a6200]">Remote-Prozess</div><h2 className="mt-3 text-2xl font-semibold tracking-tight">Hilfreich für Mandanten, die noch im Ausland sind</h2><ul className="mt-6 space-y-4 text-sm leading-7 text-[#56616b] md:text-base">{remotePoints.map((item)=><li key={item}>• {item}</li>)}</ul></div></div><div className="mt-12 ui-card-soft rounded-[2rem] px-8 py-8 md:px-10 md:py-9"><div className="text-xs uppercase tracking-[0.28em] text-[#9a6200]">Wie der Ablauf meist funktioniert</div><h2 className="mt-3 text-2xl font-semibold tracking-tight">Ein praktischer juristischer Prozess von der ersten Nachricht bis zum nächsten Schritt</h2><ol className="mt-6 space-y-4 text-sm leading-7 text-[#56616b] md:text-base">{processSteps.map((item,index)=><li key={item}>{index+1}. {item}</li>)}</ol></div></main>}
