import type { Metadata } from 'next';
import { SectionIntro } from '@/components/SiteShell';
export const metadata: Metadata = { title: 'Як ми працюємо', description: 'Як Konomic веде перший контакт, ранній розбір, документи, багатомовну комунікацію та дистанційний старт для міжнародних клієнтів на Тенерифе.', alternates: { canonical: '/uk/how-we-work' } };
const firstContact=['Для більшості нових справ перше повідомлення краще починати з WhatsApp.','Якщо ситуація ще на ранньому етапі, короткого резюме зазвичай достатньо для старту.','Якщо документи вже є, їх зазвичай можна надіслати після першого контакту.'];
const reviewLogic=['Ситуація переглядається на ранньому етапі, щоб зрозуміти правильний наступний крок.','Мета — дати ясність до того, як проблема стане дорожчою або складнішою.','Перший корисний результат зазвичай не “усе вирішено”, а зрозуміліший юридичний маршрут.'];
const documents=['Чернетки договорів або вже підписані документи','Документи по нерухомості або посилання на об’єкт','Документи щодо резиденції чи локальних реєстрацій','Чернетки по бізнесу, домовленості або комерційні документи'];
const remotePoints=['Багато міжнародних клієнтів починають ще до приїзду на Тенерифе.','Перевірка документів часто може починатися дистанційно, якщо це доречно.','WhatsApp, Telegram та email дають практичний перший крок і координацію.'];
const processSteps=['Клієнт надсилає перше повідомлення, зазвичай у WhatsApp.','Ситуація переглядається і підбирається відповідний формат консультації або перевірки.','Якщо потрібно, документи надсилаються заздалегідь.','Далі стає зрозуміло, що важливо зараз і що може зачекати.'];
export default function Page(){return <main className="ui-section ui-section-cool"><SectionIntro eyebrow="Як ми працюємо" title="Зрозуміліший процес для міжнародних клієнтів з юридичними питаннями на Тенерифе" text="Ця сторінка пояснює, як Konomic веде перший контакт, ранній розбір, документи, консультаційний процес і багатомовну комунікацію для клієнтів, яким потрібна юридична ясність до підпису, переїзду, інвестиції чи структурування бізнесу." /><div className="mt-8 ui-rule" /><div className="mt-12 grid gap-6 lg:grid-cols-2"><div className="ui-card p-8 md:p-10"><div className="text-xs uppercase tracking-[0.28em] text-[#9a6200]">Перший контакт</div><h2 className="mt-3 text-2xl font-semibold tracking-tight">Почати з короткого повідомлення, а не з довгої формальної анкети</h2><ul className="mt-6 space-y-4 text-sm leading-7 text-[#56616b] md:text-base">{firstContact.map((item)=><li key={item}>• {item}</li>)}</ul></div><div className="ui-card-dark p-8 text-white md:p-10"><div className="relative z-10"><div className="text-xs uppercase tracking-[0.28em] text-[#fca311]">Ранній розбір</div><h2 className="mt-3 text-2xl font-semibold tracking-tight">Перша мета — ясність, а не ускладнення</h2><ul className="mt-6 space-y-4 text-sm leading-7 text-white/82 md:text-base">{reviewLogic.map((item)=><li key={item}>• {item}</li>)}</ul></div></div></div><div className="mt-12 grid gap-6 lg:grid-cols-[1.05fr_0.95fr]"><div className="ui-card p-8 md:p-10"><div className="text-xs uppercase tracking-[0.28em] text-[#9a6200]">Документи</div><h2 className="mt-3 text-2xl font-semibold tracking-tight">Що клієнти часто надсилають до наступного кроку</h2><div className="mt-6 grid gap-3">{documents.map((item)=><div key={item} className="ui-card-soft px-4 py-4 text-sm text-[#33404a]">{item}</div>)}</div></div><div className="ui-card p-8 md:p-10"><div className="text-xs uppercase tracking-[0.28em] text-[#9a6200]">Дистанційний формат</div><h2 className="mt-3 text-2xl font-semibold tracking-tight">Корисно для клієнтів, які ще перебувають за кордоном</h2><ul className="mt-6 space-y-4 text-sm leading-7 text-[#56616b] md:text-base">{remotePoints.map((item)=><li key={item}>• {item}</li>)}</ul></div></div><div className="mt-12 ui-card-soft rounded-[2rem] px-8 py-8 md:px-10 md:py-9"><div className="text-xs uppercase tracking-[0.28em] text-[#9a6200]">Як зазвичай відбувається процес</div><h2 className="mt-3 text-2xl font-semibold tracking-tight">Практичний юридичний процес від першого повідомлення до наступного кроку</h2><ol className="mt-6 space-y-4 text-sm leading-7 text-[#56616b] md:text-base">{processSteps.map((item,index)=><li key={item}>{index+1}. {item}</li>)}</ol></div></main>}
