import type { Metadata } from 'next';
import { SectionIntro } from '@/components/SiteShell';
export const metadata: Metadata = { title: 'Как мы работаем', description: 'Как Konomic ведёт первый контакт, первичную проверку, документы, многоязычную коммуникацию и удалённый старт для иностранных клиентов на Тенерифе.', alternates: { canonical: '/ru/how-we-work' } };
const firstContact=['Для большинства новых вопросов первое сообщение лучше начинать с WhatsApp.','Если ситуация ранняя, короткого резюме обычно достаточно для старта.','Если документы уже есть, их обычно можно прислать после первого контакта.'];
const reviewLogic=['Ситуация смотрится на раннем этапе, чтобы понять правильный следующий шаг.','Задача — дать ясность до того, как проблема станет дороже или сложнее.','Первый полезный результат обычно не “всё решено”, а более понятный юридический маршрут.'];
const documents=['Черновики договоров или уже подписанные документы','Документы по недвижимости или ссылка на объект','Документы по резиденции или локальным регистрациям','Черновики по бизнесу, соглашения или коммерческие документы'];
const remotePoints=['Многие иностранные клиенты начинают ещё до приезда на Тенерифе.','Проверка документов часто может начаться удалённо, если это уместно.','WhatsApp, Telegram и email дают практичный первый шаг и координацию.'];
const processSteps=['Клиент отправляет первое сообщение, обычно в WhatsApp.','Ситуация смотрится и подбирается подходящий формат консультации или проверки.','Если нужно, документы присылаются заранее.','Дальше становится понятно, что важно сейчас и что может подождать.'];
export default function Page(){return <main className="ui-section ui-section-cool"><SectionIntro eyebrow="Как мы работаем" title="Более понятный процесс для иностранных клиентов с юридическими вопросами на Тенерифе" text="Эта страница объясняет, как Konomic ведёт первый контакт, раннюю проверку, документы, консультационный процесс и многоязычную коммуникацию для клиентов, которым нужна юридическая ясность до подписи, переезда, инвестиции или структуры бизнеса." /><div className="mt-8 ui-rule" /><div className="mt-12 grid gap-6 lg:grid-cols-2"><div className="ui-card p-8 md:p-10"><div className="text-xs uppercase tracking-[0.28em] text-[#9a6200]">Первый контакт</div><h2 className="mt-3 text-2xl font-semibold tracking-tight">Начать с короткого сообщения, а не с длинной формальной анкеты</h2><ul className="mt-6 space-y-4 text-sm leading-7 text-[#56616b] md:text-base">{firstContact.map((item)=><li key={item}>• {item}</li>)}</ul></div><div className="ui-card-dark p-8 text-white md:p-10"><div className="relative z-10"><div className="text-xs uppercase tracking-[0.28em] text-[#fca311]">Ранняя проверка</div><h2 className="mt-3 text-2xl font-semibold tracking-tight">Первая цель — ясность, а не усложнение</h2><ul className="mt-6 space-y-4 text-sm leading-7 text-white/82 md:text-base">{reviewLogic.map((item)=><li key={item}>• {item}</li>)}</ul></div></div></div><div className="mt-12 grid gap-6 lg:grid-cols-[1.05fr_0.95fr]"><div className="ui-card p-8 md:p-10"><div className="text-xs uppercase tracking-[0.28em] text-[#9a6200]">Документы</div><h2 className="mt-3 text-2xl font-semibold tracking-tight">Что клиенты часто присылают до следующего шага</h2><div className="mt-6 grid gap-3">{documents.map((item)=><div key={item} className="ui-card-soft px-4 py-4 text-sm text-[#33404a]">{item}</div>)}</div></div><div className="ui-card p-8 md:p-10"><div className="text-xs uppercase tracking-[0.28em] text-[#9a6200]">Удалённый формат</div><h2 className="mt-3 text-2xl font-semibold tracking-tight">Полезно для клиентов, которые ещё находятся за границей</h2><ul className="mt-6 space-y-4 text-sm leading-7 text-[#56616b] md:text-base">{remotePoints.map((item)=><li key={item}>• {item}</li>)}</ul></div></div><div className="mt-12 ui-card-soft rounded-[2rem] px-8 py-8 md:px-10 md:py-9"><div className="text-xs uppercase tracking-[0.28em] text-[#9a6200]">Как обычно идёт процесс</div><h2 className="mt-3 text-2xl font-semibold tracking-tight">Практичный юридический процесс от первого сообщения до следующего шага</h2><ol className="mt-6 space-y-4 text-sm leading-7 text-[#56616b] md:text-base">{processSteps.map((item,index)=><li key={item}>{index+1}. {item}</li>)}</ol></div></main>}
